version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8888:8888"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
